access_by_lua_block {
    local nginx_helpers = require("nginx_auth_helpers")

    local forwarded_proto = os.getenv("NGINX_X_FORWARDED_PROTO_OVERRIDE")
    local keycloak_auth_url = os.getenv("KEYCLOAK_AUTH_URL")
    local keycloak_connect_url = os.getenv("KEYCLOAK_NGINX_CONNECT_URL")
    if keycloak_connect_url == nil or keycloak_connect_url == "" then
        keycloak_connect_url = keycloak_auth_url
    end
    local keycloak_realm = os.getenv("KEYCLOAK_AUTH_REALM")
    local public_realm_url = keycloak_auth_url .. "/realms/" .. keycloak_realm
    local internal_realm_url = keycloak_connect_url .. "/realms/" .. keycloak_realm
    local opts = {
        redirect_uri = os.getenv("KEYCLOAK_AUTH_REDIRECT_URI"),
        discovery = {
            issuer = public_realm_url,
            authorization_endpoint = public_realm_url .. "/protocol/openid-connect/auth",
            token_endpoint = internal_realm_url .. "/protocol/openid-connect/token",
            userinfo_endpoint = internal_realm_url .. "/protocol/openid-connect/userinfo",
            jwks_uri = internal_realm_url .. "/protocol/openid-connect/certs",
            introspection_endpoint = internal_realm_url .. "/protocol/openid-connect/token/introspect",
            revocation_endpoint = internal_realm_url .. "/protocol/openid-connect/revoke",
            end_session_endpoint = public_realm_url .. "/protocol/openid-connect/logout",
            token_endpoint_auth_methods_supported = {"client_secret_basic", "client_secret_post"}
        },
        client_id = os.getenv("KEYCLOAK_CLIENT_ID"),
        client_secret = os.getenv("KEYCLOAK_CLIENT_SECRET"),
        session_contents = {id_token=true, access_token=true},
        ssl_verify = (os.getenv("KEYCLOAK_SSL_VERIFY") == "true") and "yes" or "no",
        accept_none_alg = false,
        renew_access_token_on_expiry = true,
        accept_unsupported_alg = false,
        revoke_tokens_on_logout = true
    }
    if forwarded_proto ~= nil and forwarded_proto ~= "" then
        opts.redirect_uri_scheme = forwarded_proto
    end

    local session_opts = {
        cookie = {
            secure = true,
            httponly = true,
            samesite = "Lax"
        }
    }

    local res, err = require("resty.openidc").authenticate(opts, nil, nil, session_opts)
    if err then
      ngx.log(ngx.ERR, "Error during authentication: " .. err)
      ngx.status = ngx.HTTP_UNAUTHORIZED
      ngx.exit(ngx.HTTP_UNAUTHORIZED)
    end

    local helper_err, username, groups, roles = nginx_helpers.check_groups_and_roles(res.id_token)
    if helper_err ~= ngx.HTTP_OK then
        ngx.status = helper_err
        ngx.exit(helper_err)
    end
    helper_err = nginx_helpers.check_rbac(res.id_token)
    if helper_err ~= ngx.HTTP_OK then
        ngx.status = helper_err
        ngx.exit(helper_err)
    end

    nginx_helpers.set_headers(username, nil, groups, roles)
}
