location ^~ /keycloak/admin {
  allow 127.0.0.1;
  allow 10.0.0.0/8;
  allow 172.16.0.0/12;
  allow 192.168.0.0/16;
  deny all;
  proxy_pass http://keycloak;
  proxy_redirect off;
  include /etc/nginx/nginx_proxy_forward_headers.conf;
}

location /keycloak {
  proxy_pass http://keycloak;
  proxy_redirect off;
  include /etc/nginx/nginx_proxy_forward_headers.conf;
}
